#!/bin/sh
################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.9
##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
##  /   /         Filename : simulate_ncsim.sh
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script SIMULATE_NCSIM.SH
## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard
##
##***************************** Beginning of Script ***************************

                
#Ensure the follwoing
#The library paths for UNISIMS_VER, SIMPRIMS_VER, XILINXCORELIB_VER,
#UNISIM, SIMPRIM, XILINXCORELIB are set correctly in the cds.lib and hdl.var files.
#Variables LMC_HOME and XILINX are set 
#Define the mapping for the work library in cds.lib file. DEFINE work ./work

mkdir work
##MGT Wrapper
ncvhdl -RELAX -V93 -work work   ../../../aurora_gtp_transceiver_tile.vhd;
ncvhdl -RELAX -V93 -work work   ../../../aurora_gtp_transceiver.vhd;

ncvhdl -RELAX -V93 -work work  ../../example_design/mgt_usrclk_source_pll.vhd;

##Example Design modules
ncvhdl -RELAX -V93 -work work   ../../example_design/frame_gen.vhd;
ncvhdl -RELAX -V93 -work work   ../../example_design/frame_check.vhd;
ncvhdl -RELAX -V93 -work work   ../../example_design/aurora_gtp_transceiver_top.vhd;
ncvhdl -RELAX -V93 -work work   ../demo_tb.vhd;

##Other modules
ncvhdl -RELAX -V93 -work work ../sim_reset_mgt_model.vhd;

##Elaborate Design
ncelab -relax -TIMESCALE 1ns/1ps -ACCESS +rwc work.DEMO_TB

ncsim +access+rw work.DEMO_TB -input @"simvision -input wave_ncsim.sv" 

