#!/bin/bash -e

. ./scripts/read_config_files

function ftp_file {
	ftp -v -n ${pc2_ip} <<HEREDOC
	user anonymous idlab@beamtest
	send logdir/${filename} idlab/${filename}
	bye
HEREDOC
}

declare filename=""
for i in $(seq 0 3); do
	filename="card${card}.channel${i}.rawdata"
	if [ -e "logdir/${filename}" ]; then
		echo
		echo "found file \"$filename\""
		ftp_file ${filename}
	fi
done

