#!/bin/bash -e

. .config
. ${location_of_status_and_log_files}/status

cd ${location_of_raw_datafiles}
declare experiment_number_string=$(printf "exp%02d" ${experiment_number})

rsync -av ${experiment_number_string} ${pc2_ip}:${pc2_destination}

