#!/bin/sh

# Clean up the results directory
rm -rf results
mkdir results

# Synthesize the Verilog wrapper files
echo 'Synthesizing Verilog example design with XST'
xst -ifn xst.scr
cp pci32_sp_v4_13_top.ngc results/

# Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
cp ../../pci32_sp_v4_13.ngc results/

# Copy the constraints file generated by Coregen
echo 'Copying files from constraints directory to results directory'
cp ../example_design/pci32_sp_v4_13_top.ucf results/

cd results

echo 'Running NGDBUILD'
ngdbuild -p xc6slx45-fgg484-3 pci32_sp_v4_13_top

echo 'Running MAP'
map pci32_sp_v4_13_top -o mapped.ncd

echo 'Running PAR'
par mapped.ncd routed.ncd

echo 'Running TRCE'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through BITGEN'
bitgen -w routed

echo 'Running NETGEN to create gate-level Verilog model'
netgen -ofmt verilog -sim -tm pci32_sp_v4_13_top -w routed.ncd routed.v
