   
REM ################################################################################
REM ##   ____  ____ 
REM ##  /   /\/   / 
REM ## /___/  \  /    Vendor: Xilinx 
REM ## \   \   \/     Version : 1.9
REM ##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
REM ##  /   /         Filename : simulate_isim.bat
REM ## /___/   /\     
REM ## \   \  /  \ 
REM ##  \___\/\___\ 
REM ##
REM ##
REM ## Script SIMULATE_ISIM.BAT
REM ## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard

REM ***************************** Beginning of Script ***************************
        
mkdir work
REM MGT Wrapper
vhpcomp -work work  ..\..\..\aurora_gtp_transceiver_tile.vhd
vhpcomp -work work  ..\..\..\aurora_gtp_transceiver.vhd

vhpcomp -work work  ..\..\example_design\mgt_usrclk_source_pll.vhd

REM Example Design modules
vhpcomp -work work  ..\..\example_design\frame_gen.vhd
vhpcomp -work work  ..\..\example_design\frame_check.vhd
vhpcomp -work work  ..\..\example_design\aurora_gtp_transceiver_top.vhd


REM Other modules
vhpcomp -work work  ..\sim_reset_mgt_model.vhd

REM Testbench file
vhpcomp -work work  ..\demo_tb.vhd


REM Compile and link source files
fuse work.DEMO_TB -L unisim -L secureip -o demo_tb.exe

REM ##--Generate waveform trace--##
.\demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim

