###############################################################################
## isim_wave.tcl
###############################################################################
onerror {resume}

wcfg new
divider add "FRAME CHECK MODULE tile0_frame_check0"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/begin_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/track_data_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/data_error_detected_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/start_of_packet_detected_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/RX_DATA
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check0/ERROR_COUNT
divider add "FRAME CHECK MODULE tile0_frame_check1"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/begin_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/track_data_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/data_error_detected_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/start_of_packet_detected_r
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/RX_DATA
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/TILE0_frame_check1/ERROR_COUNT
divider add "Loopback and Powerdown Ports"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/LOOPBACK0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/LOOPBACK1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXPOWERDOWN0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXPOWERDOWN1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXPOWERDOWN0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXPOWERDOWN1_IN
divider add "PLL Ports"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/CLK00_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/CLK01_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/GTPRESET0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/GTPRESET1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/PLLLKDET0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/PLLLKDET1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RESETDONE0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RESETDONE1_OUT
divider add "Receive Ports - 8b10b Decoder"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCHARISCOMMA0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCHARISCOMMA1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCHARISK0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCHARISK1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXDISPERR0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXDISPERR1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXNOTINTABLE0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXNOTINTABLE1_OUT
divider add "Receive Ports - Clock Correction"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCLKCORCNT0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXCLKCORCNT1_OUT
divider add "Receive Ports - Comma Detection and Alignment"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXBYTEREALIGN0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXBYTEREALIGN1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXENMCOMMAALIGN0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXENMCOMMAALIGN1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXENPCOMMAALIGN0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXENPCOMMAALIGN1_IN
divider add "Receive Ports - RX Data Path interface"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXDATA0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXDATA1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXRESET0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXRESET1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXUSRCLK0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXUSRCLK1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXUSRCLK20_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXUSRCLK21_IN
divider add "Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXN0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXN1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXP0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXP1_IN
divider add "Receive Ports - RX Elastic Buffer and Phase Alignment"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXBUFSTATUS0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXBUFSTATUS1_OUT
divider add "Receive Ports - RX Polarity Control"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXPOLARITY0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/RXPOLARITY1_IN
divider add "TX/RX Datapath Ports"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/GTPCLKOUT0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/GTPCLKOUT1_OUT
divider add "Transmit Ports - 8b10b Encoder Control"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXCHARISK0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXCHARISK1_IN
divider add "Transmit Ports - TX Buffer and Phase Alignment"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXBUFSTATUS0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXBUFSTATUS1_OUT
divider add "Transmit Ports - TX Data Path interface"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXDATA0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXDATA1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXRESET0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXRESET1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXUSRCLK0_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXUSRCLK1_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXUSRCLK20_IN
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXUSRCLK21_IN
divider add "Transmit Ports - TX Driver and OOB signalling"
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXN0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXN1_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXP0_OUT
wave add /DEMO_TB/Aurora_GTP_transceiver_top_i/Aurora_GTP_transceiver_i/tile0_Aurora_GTP_transceiver_i/TXP1_OUT


run 50 us
quit




